/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  prefix: '',
  theme: {
    borderWidth: {
      DEFAULT: '1px',
      0.5: '0.5px',
      0: '0',
      2: '2px',
      3: '3px',
      4: '4px',
      6: '6px',
      8: '8px',
    },
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        dmsans: ['DM Sans', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
        plexmono: ['"IBM Plex Mono"', 'Menlo', 'monospace'],
        plexsans: ['"IBM Plex Sans"', 'ui-sans-serif', 'system-ui'],
      },
      textDecoration: ['active', 'hover', 'focus', 'peer'],
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        'matte-dark-gray': 'var(--matte-dark-gray)',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          brand: 'var(--primary-brand)',
          blue: {
            10: 'var(--primary-blue-10)',
            20: 'var(--primary-blue-20)',
            50: 'var(--primary-blue-50)',
            100: 'var(--primary-blue-100)',
            200: 'var(--primary-blue-200)',
            500: 'var(--primary-blue-500)',
            1000: 'var(--primary-blue-1000)',
            dark: {
              10: 'var(--primary-dark-blue-10)',
              20: 'var(--primary-dark-blue-20)',
              50: 'var(--primary-dark-blue-50)',
              80: 'var(--primary-dark-blue-80)',
              100: 'var(--primary-dark-blue-100)',
              200: 'var(--primary-dark-blue-200)',
              500: 'var(--primary-dark-blue-500)',
              1000: 'var(--primary-dark-blue-1000)',
            },
          },
        },
        orange: {
          10: 'var(--accent-orange-10)',
          20: 'var(--accent-orange-20)',
          50: 'var(--accent-orange-50)',
          100: 'var(--accent-orange-100)',
          200: 'var(--accent-orange-200)',
          500: 'var(--accent-orange-500)',
          1000: 'var(--accent-orange-1000)',
        },
        feedback: {
          success: {
            10: 'var(--feedback-success-10)',
            20: 'var(--feedback-success-20)',
            50: 'var(--feedback-success-50)',
            100: 'var(--feedback-success-100)',
            200: 'var(--feedback-success-200)',
            500: 'var(--feedback-success-500)',
            1000: 'var(--feedback-success-1000)',
          },
          warning: {
            10: 'var(--feedback-warning-10)',
            20: 'var(--feedback-warning-20)',
            50: 'var(--feedback-warning-50)',
            100: 'var(--feedback-warning-100)',
            200: 'var(--feedback-warning-200)',
            500: 'var(--feedback-warning-500)',
            1000: 'var(--feedback-warning-1000)',
          },
          error: {
            10: 'var(--feedback-error-10)',
            20: 'var(--feedback-error-20)',
            50: 'var(--feedback-error-50)',
            100: 'var(--feedback-error-100)',
            200: 'var(--feedback-error-200)',
            500: 'var(--feedback-error-500)',
            1000: 'var(--feedback-error-1000)',
          },
        },
        neutral: {
          gray: {
            10: 'var(--neutral-gray-10)',
            20: 'var(--neutral-gray-20)',
            50: 'var(--neutral-gray-50)',
            100: 'var(--neutral-gray-100)',
            200: 'var(--neutral-gray-200)',
            500: 'var(--neutral-gray-500)',
            1000: 'var(--neutral-gray-1000)',
          },
          white: {
            100: 'var(--neutral-white-100)',
          },
          black: {
            800: 'var(--neutral-black-800)',
          },
        },
        status: {
          success: 'var(--status-success)',
          warning: 'var(--status-warning)',
          error: 'var(--status-error)',
          info: 'var(--status-info)',
          muted: {
            success: 'var(--status-success-muted)',
            warning: 'var(--status-warning-muted)',
            error: 'var(--status-error-muted)',
            info: 'var(--status-info-muted)',
          },
          dark: {
            success: 'var(--status-success-dark)',
            warning: 'var(--status-warning-dark)',
            error: 'var(--status-error-dark)',
            info: 'var(--status-info-dark)',
          },
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      boxShadow: {
        xs: 'var(--box-shadow-xs)',
        sm: 'var(--box-shadow-sm)',
        base: 'var(--box-shadow-base)',
        md: 'var(--box-shadow-md)',
        lg: 'var(--box-shadow-lg)',
        xl: 'var(--box-shadow-xl)',
        '2xl': 'var(--box-shadow-2xl)',
        '3xl': 'var(--box-shadow-2xl)',
        'inner-drop': 'var(--box-shadow-inner-drop)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
